name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run metrics ingestion batch (full)
      run: python -m data_pipeline.metrics_ingestion_batch

    - name: Generate cutoffs table
      run: echo "Add your cutoffs table generation step here"

    - name: Commit and push updated metrics and cutoffs tables
      run: echo "Add your commit & push step here"
