name: Metrics Ingestion Batch (Full Universe)

on:
  workflow_dispatch:
  schedule:
    # Runs at 03:00 UTC on the 1st day of every month
    - cron: "0 3 1 * *"

jobs:
  metrics-ingestion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Needed for pushing back to the repo
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run metrics ingestion batch (full)
        run: python data_pipeline/metrics_ingestion_batch.py

      - name: Generate cutoffs table
        run: python data_pipeline/gen_cutoffs_table.py

      - name: Commit and push updated metrics and cutoffs tables
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/metrics_table.csv data/cutoffs_table.csv
          git commit -m "Update metrics and cutoffs tables [skip ci]" || echo "No changes to commit"
          git push
        env:
          # GITHUB_TOKEN is automatically provided for Actions and allows pushes to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload metrics and cutoffs tables as artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics_and_cutoffs
          path: |
            data/metrics_table.csv
            data/cutoffs_table.csv
