name: Metrics Ingestion Batch (Full Universe)

on:
  workflow_dispatch:
  schedule:
    # Runs at 03:00 UTC on the 1st day of every month
    - cron: "0 3 1 * *"

jobs:
  metrics-ingestion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run metrics ingestion batch (full)
        run: python data_pipeline/metrics_ingestion_batch.py

      - name: Generate cutoffs table
        run: python data_pipeline/gen_cutoffs_table.py

      - name: Upload metrics and cutoffs tables
        uses: actions/upload-artifact@v4
        with:
          name: metrics_and_cutoffs
          path: |
            data/metrics_table.csv
            data/cutoffs_table.csv
